### ISSUE TITLE
Error - No "exports" main defined in /var/task/node_modules/devalue/package.json

### ISSUE THREAD

**Issue by elron** [sveltejs/devalue#36]
**Found duplicate:** https://github.com/sveltejs/kit/issues/6462

I get an error when trying to publish the latest sveltekit to netlify:
`Error - No "exports" main defined in /var/task/node_modules/devalue/package.json`

My Sveltekit project package.json:
```
        "devDependencies": {
		"@sveltejs/adapter-auto": "^1.0.0-next.71",
		"@sveltejs/kit": "next",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.7.0",
		"svelte": "^3.44.0",
		"svelte-check": "^2.7.1",
		"typescript": "^4.7.4",
		"vite": "^3.1.0-beta.1"
	},
```

Found more information here:
[devalue import fails with adapter-node](https://pullanswer.com/questions/devalue-import-fails-with-adapter-node)
[devalue cause crash on Netlify after update](https://pullanswer.com/questions/devalue-cause-crash-on-netlify-after-update)

**Comment by xpat** [comment]
If I read [it](https://pullanswer.com/questions/devalue-import-fails-with-adapter-node) correctly the suggestion is to remove the curly brackets around the import { devalue } as "devalue", but my import already was without the brackets.  I'm trying to figure this out still for my adapter-node project.

**Comment by filipkowal** [comment]
Following the [suggestion](https://pullanswer.com/questions/devalue-cause-crash-on-netlify-after-update#5343899):

1. Make sure that `packege.lock.json` contains `devalue@3.1.3` version
2. Add `devalue` to `noExternal` array in ssr configuration in `vite.config` like:
```js
const config = {
	plugins: [sveltekit()],
	ssr: {
		noExternal: ['devalue']
	}
};
```

**Comment by sonyarianto** [comment]
@filipkowal wow this solved my problem on Vercel build as well :) Thank you. My steps are.

- Remove `package-lock.json` (because still contains devalue 3.1.2)
- Remove `pnpm.yaml` (because still contains devalue 3.1.2)
- Run `pnpm install`
- I do your suggestion above
- Build on Vercel
- Build success!

**Comment by delaneyj** [comment]
Using straight ts-node (no vite or svelte) and hitting this same error.

`pnpm-lock.yaml` says
```yaml
/devalue/3.1.3:
    resolution: {integrity: sha512-9KO89Cb+qjzf2CqdrH+NuLaqdk9GhDP5EhR4zlkR51dvuIaiqtlkDkGzLMShDemwUy21raSMdu+kpX8Enw3yGQ==}
    dev: false
```

**Comment by secondl1ght** [comment]
Should be fixed now, see here: https://github.com/sveltejs/kit/issues/6462#issuecomment-1244680791

**Comment by W4G1** [comment]
Same issue here on devalue `4.0.1`

**Comment by elliott-with-the-longest-name-on-github** [comment]
If for some reason this is still a problem, please open a new issue -- it seems like it was the result of the ecosystem shifting slowly to ESM, which is basically not a problem anymore.
